version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: homescript-backend
    ports:
      - "8000:8000"
    volumes:
      # Monta o diretório de exemplos para refletir alterações sem precisar de rebuild
      - ./exemplos:/app/exemplos
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: homescript-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
